#!/usr/bin/env python3
"""Render reviewer wrappers and the source manifest. Exit 0 clean, 1 drift, 2 error."""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
REVIEWERS = ("alaa-reviewer", "alaa-reviewer-deep")


def policy_api(policy_root: Path | None = None):
    owner = policy_root or ROOT.parent / "alaa-prompting-guide"
    spec = importlib.util.spec_from_file_location(
        "codex_model_policy", owner / "scripts" / "codex_model_policy.py")
    if spec is None or spec.loader is None:
        raise ValueError("canonical policy loader unavailable")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module, module.load_policy(owner / "assets" / "codex-model-policy.json")


def reviewer_text(name: str, body: str, policy: dict) -> str:
    pin = policy["profiles"][name]
    description = (
        "Fresh-context independent read-only reviewer for complete orchestrated changes or "
        "user-authored work. Judges correctness, regressions, security, tests, and production "
        "risks. Never edits or fixes."
    )
    if name == "alaa-reviewer-deep":
        description = (
            "Deep correctness-review profile for complex subsystem interactions, broad failure "
            "impact, or documented insufficiency of standard review. Select instead of "
            "alaa-reviewer for the same scope. Same independent review contract; never edits."
        )
    return (
        "# Generated by scripts/render_agents.py; edit assets/reviewer-contract.md.\n"
        f'name = "{name}"\n'
        f'description = "{description}"\n'
        f'model = "{pin["model"]}"\n'
        f'model_reasoning_effort = "{pin["effort"]}"\n'
        'sandbox_mode = "read-only"\n'
        "# grant-template: materialize-live-parent-mcp\n\n"
        'developer_instructions = ' + json.dumps(body, ensure_ascii=False) + '\n'
    )


def expected_outputs(root: Path, policy: dict) -> dict[Path, bytes]:
    body = (root / "assets" / "reviewer-contract.md").read_text(encoding="utf-8")
    wrappers = {
        root / "agents" / f"{name}.toml": reviewer_text(name, body, policy).encode("utf-8")
        for name in REVIEWERS
    }
    agents = {path: path.read_bytes() for path in sorted((root / "agents").glob("*.toml"))}
    agents.update(wrappers)
    manifest = {
        "pack": "alaa-codex-orchestrator",
        "version": (root / "VERSION").read_text(encoding="utf-8").strip(),
        "managed_agents": [
            {"name": path.stem, "file": path.relative_to(root).as_posix(),
             "sha256": hashlib.sha256(data).hexdigest()}
            for path, data in sorted(agents.items())
        ],
    }
    return {**wrappers, root / "assets" / "manifest.json":
            (json.dumps(manifest, indent=2) + "\n").encode("utf-8")}


def drift(outputs: dict[Path, bytes]) -> list[Path]:
    return [path for path, data in outputs.items()
            if not path.is_file() or path.read_bytes() != data]


def self_test(policy: dict, evidence_dir: Path | None = None) -> int:
    import tempfile
    from contextlib import nullcontext
    from check_agent_grants import _toml
    if _toml is None:
        raise ValueError("renderer semantic self-test requires tomllib or tomli")
    tricky = 'Backslash \\path and """ delimiters.\nTrailing space \n'
    for name in REVIEWERS:
        parsed = _toml.loads(reviewer_text(name, tricky, policy))
        assert parsed["developer_instructions"] == tricky, "TOML must preserve canonical text"
    if evidence_dir is not None:
        # Keep explicitly requested evidence; never overwrite or clean a caller's directory.
        evidence_dir.mkdir(parents=True, exist_ok=False)
    context = (nullcontext(str(evidence_dir)) if evidence_dir is not None
               else tempfile.TemporaryDirectory(prefix="alaa-render-test-"))
    with context as directory:
        root = Path(directory)
        (root / "agents").mkdir()
        (root / "assets").mkdir()
        (root / "VERSION").write_text("fixture\n", encoding="utf-8")
        (root / "assets" / "reviewer-contract.md").write_text("contract\n", encoding="utf-8")
        outputs = expected_outputs(root, policy)
        assert len(drift(outputs)) == 3, "missing generated files must fail"
        for path, data in outputs.items():
            path.write_bytes(data)
        assert not drift(expected_outputs(root, policy)), "generated files must pass"
        wrapper = root / "agents" / "alaa-reviewer-deep.toml"
        wrapper.write_bytes(wrapper.read_bytes() + b"# manual drift\n")
        assert wrapper in drift(expected_outputs(root, policy)), "wrapper drift must fail"
        wrapper.write_bytes(outputs[wrapper])
        (root / "VERSION").write_text("changed\n", encoding="utf-8")
        assert root / "assets" / "manifest.json" in drift(expected_outputs(root, policy))
        (root / "assets" / "reviewer-contract.md").write_text("new contract\n", encoding="utf-8")
        assert all(root / "agents" / f"{name}.toml" in drift(expected_outputs(root, policy))
                   for name in REVIEWERS), "contract drift must invalidate both wrappers"
    print("RENDER SELF-TEST OK: positive output and missing, wrapper, version, contract drift fixtures")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--self-test", action="store_true")
    parser.add_argument("--policy-root", type=Path)
    parser.add_argument("--self-test-dir", type=Path,
                        help="new evidence directory to retain instead of a temporary directory")
    args = parser.parse_args()
    if args.self_test_dir is not None and not args.self_test:
        parser.error("--self-test-dir requires --self-test")
    try:
        _, policy = policy_api(args.policy_root)
        if args.self_test:
            return self_test(policy, args.self_test_dir)
        outputs = expected_outputs(ROOT, policy)
        changed = drift(outputs)
        if args.check and changed:
            for path in changed:
                print(f"generated drift: {path.relative_to(ROOT)}", file=sys.stderr)
            return 1
        if args.write:
            for path in changed:
                path.write_bytes(outputs[path])
        print(f"RENDER {'CHECK' if args.check else 'WRITE'} OK: {len(outputs)} generated files")
        return 0
    except (OSError, ValueError, KeyError, AssertionError) as exc:
        print(f"render error: {exc}", file=sys.stderr)
        return 2 if not isinstance(exc, AssertionError) else 1


if __name__ == "__main__":
    raise SystemExit(main())
