-- Intentional return/failure probes, not a production module. Requires Lua 5.4.
core.register_converters("probe_nil", function() return nil end)
core.register_converters("probe_false", function() return false end)
core.register_converters("probe_true", function() return true end)
core.register_converters("probe_error", function() error("probe-zero", 0) end)
core.register_converters("probe_error_one", function() error("probe-one") end)
core.register_action("probe_action_error", {"http-req"}, function()
    error("probe-action", 0)
end)
core.register_action("probe_action_ok", {"http-req"}, function(txn)
    txn:set_var("txn.allowed", true, true)
end)
core.register_action("probe_bool", {"http-req"}, function(txn)
    txn:set_var("txn.kind", type(txn:get_var("txn.boolean")), true)
end)

core.register_fetches("probe_fetch_nil", function() return nil end)
core.register_fetches("probe_fetch_error", function() error("fetch-error", 0) end)
core.register_action("probe_deny", {"http-req"}, function() return act.DENY end)
core.register_converters("probe_args", function(_, ...) return tostring(select("#", ...)) end)
