apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxy
spec:
  selector:
    matchLabels:
      app: haproxy
      expose-metrics: "true"
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s
