"""Render standalone profile wrappers; canonical policies alone supply pins."""
from pathlib import PurePosixPath
import json
import re


def profile_text(kind, name, metadata, body, pin, contract):
    if not isinstance(metadata, dict) or not isinstance(metadata.get("description"), str) or not metadata["description"].strip():
        raise ValueError("wrapper metadata requires a description")
    if any(key in metadata for key in ("model", "effort", "model_reasoning_effort")):
        raise ValueError("wrapper metadata cannot own model or effort")
    prefix = f"# Generated by scripts/render_agents.py; edit {contract}.\n"
    if kind == "toml":
        allowed = {"description", "sandbox_mode"}
        if set(metadata) != allowed or metadata["sandbox_mode"] not in {"read-only", "workspace-write"}:
            raise ValueError("invalid TOML wrapper metadata")
        return (prefix + f'name = {json.dumps(name)}\n'
                + f'description = {json.dumps(metadata["description"])}\n'
                + f'model = {json.dumps(pin["model"])}\n'
                + f'model_reasoning_effort = {json.dumps(pin["effort"])}\n'
                + f'sandbox_mode = {json.dumps(metadata["sandbox_mode"])}\n'
                + "# grant-template: materialize-live-parent-mcp\n\n"
                + 'developer_instructions = ' + json.dumps(body, ensure_ascii=False) + '\n')
    if kind != "yaml":
        raise ValueError("unknown wrapper format")
    allowed = {"description", "tools", "disallowedTools", "skills", "color"}
    if set(metadata) - allowed or "description" not in metadata:
        raise ValueError("invalid YAML wrapper metadata")
    head = f'---\nname: {name}\ndescription: {json.dumps(metadata["description"], ensure_ascii=False)}\n'
    head += f'model: {pin["model"]}\neffort: {pin["effort"]}\n'
    for key in ("tools", "disallowedTools", "skills", "color"):
        if key not in metadata:
            continue
        value = metadata[key]
        head += (key + ':\n' + ''.join(f'  - {item}\n' for item in value)
                 if isinstance(value, list) else f'{key}: {value}\n')
    return head + '---\n\n' + prefix + body


def expected_profiles(root, policy, kind):
    specification = json.loads((root / "assets/profile-wrappers.json").read_text(encoding="utf-8"))
    if set(specification) != {"profiles"} or not isinstance(specification["profiles"], dict):
        raise ValueError("invalid profile wrapper specification")
    managed = {name for name in policy["profiles"]
               if name.startswith("alaa-implementer") or name in {"alaa-planner", "alaa-planner-high"}}
    if set(specification["profiles"]) != managed:
        raise ValueError("wrapper specification must cover every implementation and planner profile")
    outputs = {}
    for name, entry in specification["profiles"].items():
        if not re.fullmatch(r"alaa-[a-z0-9-]+", name) or set(entry) != {"contract", "metadata"}:
            raise ValueError("invalid profile wrapper entry")
        contract = entry["contract"]
        if not isinstance(contract, str) or "\\" in contract or ":" in contract:
            raise ValueError("contract must be a repository-relative path")
        relative = PurePosixPath(contract)
        if relative.is_absolute() or ".." in relative.parts or str(relative) != contract:
            raise ValueError("contract must be a canonical relative path")
        path = (root / contract).resolve()
        if not path.is_relative_to(root.resolve()) or not path.is_file():
            raise ValueError(f"invalid contract path: {contract}")
        body = path.read_text(encoding="utf-8")
        text = profile_text(kind, name, entry["metadata"], body, policy["profiles"][name], contract)
        suffix = ".toml" if kind == "toml" else ".md"
        outputs[root / "agents" / (name + suffix)] = text.encode("utf-8")
    return outputs
