"""Render standalone profile wrappers; canonical policy registers model-neutral role identities."""
from pathlib import PurePosixPath
import json
import re
try:
    import tomllib
except ModuleNotFoundError:
    try:
        import tomli as tomllib
    except ModuleNotFoundError:
        tomllib = None


def _agent_data(text):
    """Read source wrappers; without a parser accept only their top-level strings.

    Preserve multiline tokens verbatim for before/after comparison. This fallback
    does not interpret instructions or accept installed tables as source wrappers.
    """
    if tomllib is not None:
        return tomllib.loads(text)
    token = re.compile(
        r'\s*(?:#[^\n]*(?:\n|$)|(?P<key>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*'
        r'(?P<value>""".*?"""|"(?:[^"\\\n]|\\.)*")\s*(?:#[^\n]*)?(?:\n|$))', re.S)
    data, position = {}, 0
    while text[position:].strip():
        match = token.match(text, position)
        if match is None:
            raise ValueError("unsupported source TOML; use tomllib or tomli for richer syntax")
        key, value = match.group('key', 'value')
        if key is not None:
            if key in data:
                raise ValueError("duplicate source TOML key")
            data[key] = value if value.startswith('"""') else json.loads(value)
        position = match.end()
    return data


def profile_text(kind, name, metadata, body, pin, contract):
    if not isinstance(metadata, dict) or not isinstance(metadata.get("description"), str) or not metadata["description"].strip():
        raise ValueError("wrapper metadata requires a description")
    if any(key in metadata for key in ("model", "effort", "model_reasoning_effort")):
        raise ValueError("wrapper metadata cannot own model or effort")
    if pin.get("selection_mode") != "task-selected" or any(key in pin for key in ("model", "effort")):
        raise ValueError("wrapper requires model-neutral task-selected profile")
    prefix = f"# Generated by scripts/render_agents.py; edit {contract}.\n"
    if kind == "toml":
        allowed = {"description", "sandbox_mode"}
        if set(metadata) != allowed or metadata["sandbox_mode"] not in {"read-only", "workspace-write"}:
            raise ValueError("invalid TOML wrapper metadata")
        return (prefix + f'name = {json.dumps(name)}\n'
                + f'description = {json.dumps(metadata["description"])}\n'
                + f'sandbox_mode = {json.dumps(metadata["sandbox_mode"])}\n'
                + "# grant-template: materialize-live-parent-mcp\n\n"
                + 'developer_instructions = ' + json.dumps(body, ensure_ascii=False) + '\n')
    if kind != "yaml":
        raise ValueError("unknown wrapper format")
    allowed = {"description", "tools", "disallowedTools", "skills", "color"}
    if set(metadata) - allowed or "description" not in metadata:
        raise ValueError("invalid YAML wrapper metadata")
    head = f'---\nname: {name}\ndescription: {json.dumps(metadata["description"], ensure_ascii=False)}\n'
    for key in ("tools", "disallowedTools", "skills", "color"):
        if key not in metadata:
            continue
        value = metadata[key]
        head += (key + ':\n' + ''.join(f'  - {item}\n' for item in value)
                 if isinstance(value, list) else f'{key}: {value}\n')
    return head + '---\n\n' + prefix + body


def expected_profiles(root, policy, kind):
    specification = json.loads((root / "assets/profile-wrappers.json").read_text(encoding="utf-8"))
    if set(specification) != {"profiles"} or not isinstance(specification["profiles"], dict):
        raise ValueError("invalid profile wrapper specification")
    managed = {name for name in policy["profiles"]
               if name.startswith("alaa-implementer") or name in {"alaa-planner", "alaa-planner-high"}}
    if set(specification["profiles"]) != managed:
        raise ValueError("wrapper specification must cover every implementation and planner profile")
    outputs = {}
    for name, entry in specification["profiles"].items():
        if not re.fullmatch(r"alaa-[a-z0-9-]+", name) or set(entry) != {"contract", "metadata"}:
            raise ValueError("invalid profile wrapper entry")
        contract = entry["contract"]
        if not isinstance(contract, str) or "\\" in contract or ":" in contract:
            raise ValueError("contract must be a repository-relative path")
        relative = PurePosixPath(contract)
        if relative.is_absolute() or ".." in relative.parts or str(relative) != contract:
            raise ValueError("contract must be a canonical relative path")
        path = (root / contract).resolve()
        if not path.is_relative_to(root.resolve()) or not path.is_file():
            raise ValueError(f"invalid contract path: {contract}")
        body = path.read_text(encoding="utf-8")
        text = profile_text(kind, name, entry["metadata"], body, policy["profiles"][name], contract)
        suffix = ".toml" if kind == "toml" else ".md"
        outputs[root / "agents" / (name + suffix)] = text.encode("utf-8")
    return outputs


def neutral_agent_text(kind, text, profile):
    """Remove only parsed executable pins; preserve role authority and loaded body."""
    if not isinstance(profile, dict) or profile.get("selection_mode") != "task-selected" or any(key in profile for key in ("model", "effort")):
        raise ValueError("task-selected model-neutral profile required")
    if kind == "toml":
        data = _agent_data(text)
        keys = {"model", "model_reasoning_effort", "effort"}
        for key in keys & data.keys():
            if not isinstance(data[key], str):
                raise ValueError("executable pins must be scalar strings")
        # These supported wrappers use top-level scalar pins. Never match body strings.
        lines = text.splitlines(keepends=True)
        active, output = True, []
        for line in lines:
            if re.match(r'^\s*developer_instructions\s*=', line) or re.match(r'^\s*\[', line):
                active = False
            if active and re.match(r'^\s*(?:model|model_reasoning_effort|effort)\s*=', line):
                continue
            output.append(line)
        result = ''.join(output)
        actual = _agent_data(result)
        if actual != {key:value for key,value in data.items() if key not in keys}:
            raise ValueError("neutral projection changed authority/body or left pins")
        return result
    if kind != "yaml":
        raise ValueError("unknown wrapper format")
    from check_claude_model_policy import parse_agent
    data = parse_agent(text)
    match = re.match(r"\A---\s*\n(.*?)\n---\s*(?:\n|$)", text, re.S)
    if not match:
        raise ValueError("missing frontmatter")
    keys = {"model", "effort", "model_reasoning_effort"}
    if any(not isinstance(data[key], str) for key in keys & data.keys()):
        raise ValueError("executable pins must be scalar strings")
    head = ''.join(line for line in match[1].splitlines(keepends=True)
                   if not re.match(r'^(?:model|effort|model_reasoning_effort):', line))
    result = text[:match.start(1)] + head + text[match.end(1):]
    if parse_agent(result) != {key:value for key,value in data.items() if key not in keys}:
        raise ValueError("neutral projection changed authority or left pins")
    return result


def self_test():
    import runpy
    import sys
    from pathlib import Path
    from unittest.mock import patch
    from codex_model_policy import load_policy as codex_policy
    from claude_model_policy import load_policy as claude_policy
    for kind, policy in (("toml", codex_policy()), ("yaml", claude_policy())):
        for role, profile in policy["profiles"].items():
            if profile["selection_mode"] != "task-selected":
                continue
            if kind == "toml":
                text = f'name = "{role}"\nmodel = "gpt-6-astra"\nmodel_reasoning_effort = "high"\nsandbox_mode = "read-only"\ndeveloper_instructions = "model = keep this body"\n'
            else:
                text = f'---\nname: {role}\nmodel: claude-fable-5-1\neffort: high\ntools: Read, Grep\n---\nmodel: keep this body\n'
            neutral = neutral_agent_text(kind, text, profile)
            assert "keep this body" in neutral
            assert neutral_agent_text(kind, neutral, profile) == neutral
            try:
                neutral_agent_text(kind, text, {**profile, "model": "fixed"})
            except ValueError:
                pass
            else:
                raise AssertionError("accepted fixed profile")
    for kind, text in (("toml", 'name = "x"\nmodel = ["bad"]\n'),
                       ("yaml", '---\nname: x\nmodel: [bad]\n---\nbody')):
        try:
            neutral_agent_text(kind, text, {"selection_mode":"task-selected"})
        except ValueError:
            pass
        else:
            raise AssertionError("accepted ambiguous pin")
    # Simulate absent stdlib support without requiring another installed Python.
    with patch.dict(sys.modules, {"tomllib": None, "tomli": None}):
        fallback = runpy.run_path(__file__, run_name="projection_without_toml")
    profile = {"selection_mode": "task-selected"}
    sources = Path(__file__).resolve().parents[2] / "alaa-codex-orchestrator/agents"
    for path in sources.glob("*.toml"):
        text = path.read_text(encoding="utf-8")
        assert fallback["neutral_agent_text"]("toml", text, profile) == neutral_agent_text("toml", text, profile)
    sample = 'name = "x"\nmodel = "old"\ndeveloper_instructions = "body"\n'
    assert 'model =' not in fallback["neutral_agent_text"]("toml", sample, profile)
    for invalid in ('name = "x"\nname = "y"\n', 'model = ["bad"]\n', '[table]\nname = "x"\n'):
        try:
            fallback["neutral_agent_text"]("toml", invalid, profile)
        except ValueError:
            pass
        else:
            raise AssertionError("fallback accepted unsupported/duplicate source syntax")
    if tomllib is not None:
        with patch.dict(sys.modules, {"tomllib": None, "tomli": tomllib}):
            backport = runpy.run_path(__file__, run_name="projection_with_backport")
        assert backport["tomllib"] is tomllib
        assert backport["neutral_agent_text"]("toml", sample, profile) == neutral_agent_text("toml", sample, profile)
    print("OK: all-role neutral projections preserve authority/body and reject fixed/ambiguous controls")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--self-test", action="store_true", required=True)
    parser.parse_args()
    from codex_model_policy import PolicyLoadError
    from claude_model_policy import CannotRun
    import sys
    try:
        self_test()
    except (PolicyLoadError, CannotRun, OSError, UnicodeError) as exc:
        print(f"could not run: {exc}", file=sys.stderr)
        raise SystemExit(2)
    except (ValueError, AssertionError) as exc:
        print(f"FINDINGS: {exc}", file=sys.stderr)
        raise SystemExit(1)
